In [1]:
import numpy as np
import pandas as pd
import sympy
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
print(np.__version__)

1.19.2


In [5]:
#np? we can ? to see documentation of any module like the code following # sign

In [54]:
# creating an array in Numpy
arr= np.array([1,2,3,4,5,6])
print(arr.shape)
print(arr)
arr2=np.random.rand(20).reshape(5,4) # to generate an array of random numbers
arr_int= np.random.randint(20, size=(5,4))
print(arr2)

(6,)
[1 2 3 4 5 6]
[[0.85762553 0.94977903 0.56168686 0.17878052]
 [0.77025193 0.49238104 0.63125307 0.83949792]
 [0.4610394  0.49794007 0.67941112 0.65078591]
 [0.26879524 0.06732467 0.77144514 0.48098413]
 [0.32920641 0.51064106 0.26362883 0.31051155]]


In [57]:
np.random.seed(20) # seed is used to set and random variable so array genertaed will be same every time
arr4= np.random.rand(20)
print(arr4)
print(arr_int.shape)

[0.5881308  0.89771373 0.89153073 0.81583748 0.03588959 0.69175758
 0.37868094 0.51851095 0.65795147 0.19385022 0.2723164  0.71860593
 0.78300361 0.85032764 0.77524489 0.03666431 0.11669374 0.7512807
 0.23921822 0.25480601]
(5, 4)


In [59]:
#spliting and merging or joining two arrays
arr5= np.array([[10,20,30,85],[10,52,45,65]])
display(arr5)

array([[10, 20, 30, 85],
       [10, 52, 45, 65]])

In [72]:
arr6=np.hstack([arr5,arr5])#np.concatenate([arr5,arr5], axis=0) # axis 1 means horizontal or x axis 0 means y or vertical
#similar can be achived using np.vstack for vertical and np.hstack for horizontal stack
arr6
x1=np.array([1,2,3,4,5,6,7,8,9])
x2= np.split(x1, [2,5,7,9])
#np.split?
print(x2)
#np.split?

[array([1, 2]), array([3, 4, 5]), array([6, 7]), array([8, 9]), array([], dtype=int32)]


In [88]:
#mat= np.random.randint(9, size=(3,3))
mat=np.arange(9).reshape(3,3) #matrix with 0 determinant
print(np.linalg.det(mat))
print(mat)
#print(np.linalg.inv(mat))
np.max(mat)

0.0
[[0 1 2]
 [3 4 5]
 [6 7 8]]


8

In [85]:
x= sympy.Symbol('x')
fx= 2*x**3+5*x+ 15
print(np.min(fx).doit())

2*x**3 + 5*x + 15
