In [1]:
import numpy as np
import pandas as pd
import sympy
import matplotlib.pyplot as plt
import seaborn as sns
import fod

1.19.2
hello gurwinder
(6,)
[1 2 3 4 5 6]
[[0.71845572 0.75209709 0.69614745 0.67233011]
 [0.712845   0.00539894 0.27823921 0.0199967 ]
 [0.09494486 0.02920028 0.09633289 0.82131226]
 [0.65008519 0.65891774 0.31798395 0.95295033]
 [0.3513835  0.67345764 0.58903871 0.66692981]]
[0.5881308  0.89771373 0.89153073 0.81583748 0.03588959 0.69175758
 0.37868094 0.51851095 0.65795147 0.19385022 0.2723164  0.71860593
 0.78300361 0.85032764 0.77524489 0.03666431 0.11669374 0.7512807
 0.23921822 0.25480601]
(5, 4)


array([[10, 20, 30, 85],
       [10, 52, 45, 65]])

[array([1, 2]), array([3, 4, 5]), array([6, 7]), array([8, 9]), array([], dtype=int32)]
0.0
[[0 1 2]
 [3 4 5]
 [6 7 8]]
2*x**3 + 5*x + 15


In [2]:
print(np.__version__)

1.19.2


In [3]:
f="great it worked"
fod.hellop(f)

great it worked


In [5]:
y="hello gurwinder"
fod.hellop(y)
#np? we can ? to see documentation of any module like the code following # sign

hello gurwinder


In [8]:
# creating an array in Numpy
arr= np.array([1,2,3,4,5,6])
print(arr.shape)
print(arr)
arr2=np.random.rand(20).reshape(5,4) # to generate an array of random numbers
arr_int= np.random.randint(20, size=(5,4))
print(arr2)
print(arr_int)

(6,)
[1 2 3 4 5 6]
[[0.83889446 0.03553703 0.12144377 0.89100806]
 [0.51509223 0.92441901 0.58124263 0.77325639]
 [0.42267689 0.82546475 0.38540456 0.35434596]
 [0.42807852 0.39506518 0.84462971 0.37382381]
 [0.37158098 0.41594296 0.42454448 0.66280484]]
[[ 9 10  0 15]
 [15 10  4  3]
 [12 10  2  7]
 [ 0 11 15 18]
 [ 7 11  7  5]]


In [14]:
np.random.seed(20) # seed is used to set and random variable so array genertaed will be same every time
arr4= np.random.rand(20)
print(arr4)
print(arr_int.shape)

[0.5881308  0.89771373 0.89153073 0.81583748 0.03588959 0.69175758
 0.37868094 0.51851095 0.65795147 0.19385022 0.2723164  0.71860593
 0.78300361 0.85032764 0.77524489 0.03666431 0.11669374 0.7512807
 0.23921822 0.25480601]
(5, 4)


In [15]:
#spliting and merging or joining two arrays
arr5= np.array([[10,20,30,85],[10,52,45,65]])
display(arr5)

array([[10, 20, 30, 85],
       [10, 52, 45, 65]])

In [17]:
arr6=np.hstack([arr5,arr5])#np.concatenate([arr5,arr5], axis=0) # axis 1 means horizontal or x axis 0 means y or vertical
#similar can be achived using np.vstack for vertical and np.hstack for horizontal stack
print(arr6)
x1=np.array([1,2,3,4,5,6,7,8,9])
x2= np.split(x1, [2,5,7,9])
#np.split?
print(x2)
#np.split?

[[10 20 30 85 10 20 30 85]
 [10 52 45 65 10 52 45 65]]
[array([1, 2]), array([3, 4, 5]), array([6, 7]), array([8, 9]), array([], dtype=int32)]


In [22]:
#mat= np.random.randint(9, size=(3,3))
mat=np.arange(9).reshape(3,3) #matrix with 0 determinant
print(np.linalg.det(mat))
print(mat)
#print(np.linalg.inv(mat))
np.max(mat)


0.0
[[0 1 2]
 [3 4 5]
 [6 7 8]]


AttributeError: module 'numpy' has no attribute 'inverse'

In [23]:
x= sympy.Symbol('x')
fx= 2*x**3+5*x+ 15
print(np.min(fx).doit())

2*x**3 + 5*x + 15


In [ ]:
help(np.exp)

In [9]:
ab= np.arange(9).reshape(3,3)
ba= np.random.randint(10, size=(3,3))
print(ab)
print(ba)
print(ab*ba)
print(ab@ba)
print(np.dot(ab, ba))
print(np.matmul(ab, ba))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[6 9 4]
 [6 4 8]
 [6 2 3]]
[[ 0  9  8]
 [18 16 40]
 [36 14 24]]
[[ 18   8  14]
 [ 72  53  59]
 [126  98 104]]
[[ 18   8  14]
 [ 72  53  59]
 [126  98 104]]
[[ 18   8  14]
 [ 72  53  59]
 [126  98 104]]
